// IMPORT
/* HEADER */
/* HERO */
/* ABOUT ME */
/* My Offered Services */
/* ANIMATED NUMBER COUNTER */
/* PORTFOLIO */
/* TESTIMONIALS */
/* PRICE AREA */
/* RECENT BLOG */
/* BRANDS AREA */
/* FOOTER */


// FUNKCIJU PANAUDOJIMAS

/* HEADER */
/* HERO */
/* ABOUT ME */
/* My Offered Services */
/* ANIMATED NUMBER COUNTER */
/* PORTFOLIO */
/* TESTIMONIALS */
/* PRICE AREA */
/* RECENT BLOG */
/* BRANDS AREA */
/* FOOTER */